#
# server
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.tomcat.threads.max
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    accesslog:
      directory: logs
      enabled: true
      max-days: 7
      pattern: '%{X-Forwarded-For}i %h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"'
    basedir: tomcat
    max-connections: 8192
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB
    mbeanregistry:
      enabled: true
    remoteip:
      host-header: X-Forwarded-Host
      port-header: X-Forwarded-Port
      protocol-header: X-Forwarded-Proto
      remote-ip-header: X-Forwarded-For
    threads:
      max: 200
#
# actuator
#
management:
  server:
    port: 8081 # ${server.port}
  health:
    defaults:
      enabled: false
    diskspace:
      enabled: true
    memory:
      enabled: true
  endpoint:
    health:
      show-details: always
      access: read_only
    info:
      access: read_only
    prometheus:
      access: read_only
  endpoints:
    access:
      default: read_only
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - prometheus
#
# spring
spring:
  application:
    name: hello-world
  profiles:
    active: debug
  thymeleaf:
    enabled: true
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  freemarker:
    charset: UTF-8
    content-type: text/plain
    enabled: false
    suffix: .ftl
    template-loader-path: classpath:/freemarker/
  jackson:
    serialization:
      write-dates-as-timestamps: true
  mvc:
    contentnegotiation:
      favor-parameter: true
      parameter-name: format
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  security:
    ignored-url: /,/index.html,/robots.txt,/error,/actuator/**,/captcha.jpg,/wechat,/wechat/**
    user:
      name: admin
      password: '{bcrypt}$2y$05$ThCznak4WVfGXBqLIoO1IenzRCVsbazv.hRIfVXE6hcLxVOOcNX9e'
#
# log
logging:
  file:
    access-name: ./logs/${spring.application.name}-access.log
    name: ./logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      clean-history-on-start: true
      file-name-pattern: ${logging.file.name}.%d{yyyyMMdd}.%i
      max-file-size: 100MB
      max-history: 7
      total-size-cap: 10GB
  pattern:
    correlation: '[%X{X-REQUEST-ID:--}] '
  level:
    root: info
    access: trace
    com.mudcode: debug
