#debug: true
spring.profiles.active: debug
#
# application
spring.application.name: hello-world
#
# server
# https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.server.server.tomcat.threads.max
server.port: 18080
server.servlet.context-path: /
server.tomcat.basedir: tomcat
server.tomcat.threads.max: 200
server.tomcat.max-connections: 8192
server.tomcat.max-http-form-post-size: 10MB
server.tomcat.max-swallow-size: 10MB
server.tomcat.mbeanregistry.enabled: true
server.tomcat.accesslog.enabled: true
server.tomcat.accesslog.directory: logs
server.tomcat.accesslog.max-days: 7
# org.apache.catalina.valves.Constants.AccessLog
server.tomcat.accesslog.pattern: "%{X-Forwarded-For}i %h %l %u %t \"%r\" %s %b \"%{Referer}i\" \"%{User-Agent}i\""
server.tomcat.remoteip.host-header: X-Forwarded-Host
server.tomcat.remoteip.port-header: X-Forwarded-Port
server.tomcat.remoteip.remote-ip-header: X-Forwarded-For
#server.tomcat.remoteip.protocol-header-https-value: https
server.tomcat.remoteip.protocol-header: X-Forwarded-Proto
# spring servlet file upload
spring.servlet.multipart.max-file-size: 200MB
spring.servlet.multipart.max-request-size: 200MB
# spring mvc
spring.mvc.contentnegotiation.parameter-name: format
spring.mvc.contentnegotiation.favor-parameter: true
# json write-dates-as-timestamps
spring.jackson.serialization.write-dates-as-timestamps: true
#
# actuator
#
management:
  server:
    port: 8081 # ${server.port}
  health:
    defaults:
      enabled: false
    diskspace:
      enabled: true
    memory:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
    info:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    enabled-by-default: false
    web:
      base-path: /actuator
      exposure:
        include:
          - health
          - info
          - prometheus
#
# spring thymeleaf
spring.thymeleaf.enabled: true
spring.thymeleaf.prefix: classpath:/templates/
spring.thymeleaf.suffix: .html
spring.thymeleaf.encoding: UTF-8
# spring freemarker
spring.freemarker.enabled: false
spring.freemarker.template-loader-path: classpath:/freemarker/
spring.freemarker.suffix: .ftl
spring.freemarker.charset: UTF-8
spring.freemarker.content-type: text/plain
#
# spring security
spring.security.user.name: admin
spring.security.user.password: "{bcrypt}$2y$05$ThCznak4WVfGXBqLIoO1IenzRCVsbazv.hRIfVXE6hcLxVOOcNX9e"
spring.security.ignored-url: /,/index.html,/robots.txt,/error,/actuator/**,/captcha.jpg,/wechat,/wechat/**
#
# log
logging.file.name: ./logs/${spring.application.name}.log
logging.file.access-name: ./logs/${spring.application.name}-access.log
logging.logback.rollingpolicy.file-name-pattern: ${logging.file.name}.%d{yyyyMMdd}.%i
logging.logback.rollingpolicy.clean-history-on-start: true
logging.logback.rollingpolicy.max-file-size: 100MB
logging.logback.rollingpolicy.max-history: 7
logging.logback.rollingpolicy.total-size-cap: 10GB
logging.pattern.correlation: "[%X{X-REQUEST-ID:--}] "
# log level
logging.level.root: info
logging.level.access: trace
logging.level.com.mudcode: debug

