# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  schedule:
    # https://pubs.opengroup.org/onlinepubs/9699919799/utilities/crontab.html#tag_20_25_07
    - cron: "0 1 * * 1"

jobs:
  mvn_package:
    strategy:
      matrix:
        java-version: [ "17" ]
        java-distribution: [ "temurin" ]
        os: [ "ubuntu-22.04" ]
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        # https://github.com/marketplace/actions/setup-java-jdk
        with:
          java-version: ${{ matrix.java-version }}
          distribution: ${{ matrix.java-distribution }}
          cache: maven
      - run: mvn clean package -U
